version: '2'

services:
    django:
        build:
            context: .
            dockerfile: docker/Dockerfile-django
        volumes:
            - "./projement:/app"
        environment:
            - PYTHONUNBUFFERED=0
            - PYTHONPYCACHEPREFIX=../__pycache__
        ports:
            - "8000:8000"
        depends_on:
            - db 
        command: python manage.py runserver 0.0.0.0:8000

    node:
        build:
            context: .
            dockerfile: docker/Dockerfile-node
        volumes:
            - ".data/node_modules:/app/node_modules"
            - "./projement:/app"
            
    db:
        image: postgres
        expose:
          - 5432
        volumes:
          - pg_data:/var/lib/postgresql/data
          - pg_backups:/pg_backups
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=test


volumes:
  pg_data: {}
  pg_backups: {}

