# Generated by Django 2.2.7 on 2022-12-27 08:04

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('end_date'), descending=True, nulls_first=True), 'title']},
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual design hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual development hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_testing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual testing hours'),
        ),
    ]
